fullname: Grigoriev Semyon
favicon: /assets/images/favicon.svg
logo: /assets/images/image.png

show_info: true
age: 20 y.o.
location: Russia
language: Russian, English

show_contacts: true
mailto: mailto:semen603089@mail.ru
cv_pdf_link: https://raw.githubusercontent.com/Annndruha/annndruha.github.io/main/pdf/cv_pdf.pdf

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme
