fullname: Grigoriev Semyon
favicon: /assets/images/favicon.svg
logo: /assets/images/image.jpeg

show_info: true
age: 20 y.o.
location: Russia
language: Russian, English

show_contacts: true
mailto: mailto:semen603089@mail.ru
cv_pdf_link: https://github.com/grigoriev-semyon/grigoriev-semyon.github.io/raw/main/pdf/cv-pdf.pdf

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme
